// Ids of items that aren't blocks (256 and up; 0-255 are the blocks). Kept
// apart from items.js so blocks.js can name them without a circular import.
// Never renumber.
import { METALS, FLUID, ELEMENTAL } from './config.js';

export const ITEM = {
  WOOD_HAMMER: 256,
  LADDER: 257,
  DOOR: 258,
  IRON_INGOT: 259,
  STONE_HAMMER: 260,
  IRON_HAMMER: 261,
  WOOD_SWORD: 262,
  STONE_SWORD: 263,
  IRON_SWORD: 264,
  BOW: 265,
  LEATHER: 266,
  BEEF: 267,
  EMPTY_BUCKET: 268,
  WATER_BUCKET: 269,
  COOKED_BEEF: 270,
  LEATHER_ARMOR: 271,
  IRON_ARMOR: 272,
  GLIDER: 273,
  TREE_SEED: 274,
  GOLDEN_BEEF: 275,
  WIND_BOOTS: 276,
  SPRING_BOOTS: 277,
  HEART_AMULET: 278,
  MENDING_CHARM: 279,
  EMBER_HEART: 280,
  RIFT_ORB: 281,
  WIND_AXE: 282,
  ICE_SWORD: 283,
  CROSSBOW: 284,
  ROPE_BUNDLE: 285,
  GRAPPLING_HOOK: 286,
  DRAGON_SCALE: 287,
  SILK: 288,
  DRAGONSCALE_ARMOR: 289,
  // ID 290 was the Flight Orb; reserved.
  COW_EGG: 291,
  DRAGON_EGG: 292,
  CRAWLER_EGG: 293,
  VOID_EEL_EGG: 294,
  GOBLIN_WORKER_EGG: 295,
  GOBLIN_KING_EGG: 296,
  // ID 297 was the Builder egg; reserved.
  GOBLIN_SOLDIER_EGG: 298,
  GOBLIN_ARCHER_EGG: 299,
  // IDs 301, 303 and 304 remain reserved.
  GOBLIN_BRUTE_EGG: 302,
  REINFORCED_DOOR: 300,
  CHARCOAL: 305,
  MONKEY_EGG: 306,
  WISE_MONKEY_EGG: 307,
  ANCIENT_WATER_MONKEY_EGG: 308,
  ANCIENT_LIGHTNING_MONKEY_EGG: 309,
  GOBLIN_TOTEM_EGG: 310,
  COPPER_INGOT: METALS.itemIds.copperIngot,
  TIN_INGOT: METALS.itemIds.tinIngot,
  BRONZE_INGOT: METALS.itemIds.bronzeIngot,
  BRONZE_HAMMER: METALS.itemIds.bronzeHammer,
  BRONZE_ARMOR: METALS.itemIds.bronzeArmor,
  BRONZE_SWORD: METALS.itemIds.bronzeSword,
  IRON_DUST: FLUID.itemIds.ironDust,
  COPPER_DUST: FLUID.itemIds.copperDust,
  TIN_DUST: FLUID.itemIds.tinDust,
  LAVA_BUCKET: ELEMENTAL.itemIds.lavaBucket,
  ANCIENT_FIRE_MONKEY_EGG: ELEMENTAL.itemIds.ancientFireMonkeyEgg,
  DRAGON_CROWN: ELEMENTAL.itemIds.dragonCrown,
  DRAGON_HEART: ELEMENTAL.itemIds.dragonHeart,
};
